### ISSUE TITLE
Can ChangeStar be used for general CD?  

### ISSUE THREAD

**Issue by Richardych** [Z-Zheng/ChangeStar#10]
hi,

Thanks for the great work.
I wonder, can this work be used for general change detection? i.e., multi-class not just single class.

If yes, do you have done the experiments? Thanks!

**Comment by Z-Zheng** [comment]
> hi,
> 
> Thanks for the great work. I wonder, can this work be used for general change detection? i.e., multi-class not just single class.
> 
> If yes, do you have done the experiments? Thanks!

Of course, ChangeStar is a unified architecture for change detection, e.g., binary, semantic change detection.
Under bitemporal and semantic supervision, it works well.

**Comment by Z-Zheng** [comment]
> BTW, how do you prepare the "targets" for tier3 of xview2? Thanks!

We have released these files here https://github.com/Z-Zheng/ChangeStar/releases/download/v0.1.0/xView2-tier3-targets.zip

Hope this helps.
