### ISSUE TITLE
可视化效果

### ISSUE THREAD

**Issue by coocooon** [Z-Zheng/ChangeStar#11]
武大的大佬好，能否百忙之中分享一下可视化程序，感谢感谢

**Comment by Z-Zheng** [comment]
您说的是什么可视化？如果只是对预测图上色的话，就简单用PIL库上色就可以

**Comment by coocooon** [comment]
![2021-11-04 17-09-06 的屏幕截图](https://user-images.githubusercontent.com/64255092/140287556-33b9eae3-7e6d-4538-8547-411ed3000220.png)
感谢大佬,我简单的给乘以255可视化出来是这样的,应该差不多

**Comment by LiuXG0322** [comment]
> Hello, bro! Can you share your the testing demo for me? Thanks! My Email is 965377955@qq.com.
