### ISSUE TITLE
Cant't download the xView2 dataset.

### ISSUE THREAD

**Issue by Classmate-Huang** [Z-Zheng/ChangeStar#13]
你好，我无法下载那个xView2的数据集，每次下到大概1/3就会报错，显示网络错误。请问有什么好的建议吗？

国内用户，Chrome浏览器和迅雷都试过了。

**Comment by Z-Zheng** [comment]
1. 可以尝试用一些VPN再下载
2. 可以向xView2团队发邮件反馈一下数据集下载的问题，看看他们是否有更好的方案
