### ISSUE TITLE
关于使用ever库中的infer_tool工具

### ISSUE THREAD

**Issue by Yue-Wa** [Z-Zheng/ChangeStar#18]
大佬您好！
       我在使用ever库中的infer_tool工具中的build_and_load_from_file函数加载模型数据和权重时，出现如下错误：
![dee0d9c3efa1ccdf97faa994c390578](https://user-images.githubusercontent.com/72966878/165751423-d292834b-5a67-4d82-96ee-8856071a157b.png)
       显示“ChangeStar不支持”，你有什么解决办法么，或者知道错误出现在哪么。感谢！！

**Comment by Yue-Wa** [comment]
![f770c76b02dec52ff160ffbc6d956bb](https://user-images.githubusercontent.com/72966878/165751882-06518ff4-54f0-4840-aca0-d6afcaafdd4a.png)
部分代码如下。

**Comment by Z-Zheng** [comment]
在程序执行一开始调用一下注册模块的函数，就能把module文件夹下的模型都注册上
即，
```python
if __name == '__main__':
    er.registry.register_modules()
```
