### ISSUE TITLE
How to get the bitemporal images' labels if the model is trained on LEVIR-CD dataset?

### ISSUE THREAD

**Issue by SONGLEI-arch** [Z-Zheng/ChangeStar#19]
Hello, I'm very interested in your work, but I encountered a problem in the process of research. If the model is trained on the LEVIR-CD dataset, how to obtain the changed labels when there are no segmentation maps for each bitemporal image in the dataset? I would appreciate it if you could solve my problems.

**Comment by Z-Zheng** [comment]
I guess you trained the model based on the bitemporal supervised setting.
If so, ChangeStar directly outputs the change map without object segmentation.

**Comment by SONGLEI-arch** [comment]
Thank you very much for your reply.
