### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by LIUZIJING-CHN** [Z-Zheng/ChangeStar#2]
Excuse me,
I want to know how this module behave inference after training the model. And if you can offer an link for usage of 'ever' Lib, that will be fantastic

**Comment by Z-Zheng** [comment]
The evaluation will be called automatically after training.
A standalone evaluation script will be added in the future.
The evaluation function for bitemporal supervised CD can be seen [here](https://github.com/Z-Zheng/ChangeStar/blob/41aa557ceb893ee544659c0563c9e81bf0816401/train_sup_change.py#L13)
