### ISSUE TITLE
ChangeMask: Deep multi-task encoder-transformer-decoder architecture for semantic change detection

### ISSUE THREAD

**Issue by linyiyuan11** [Z-Zheng/ChangeStar#24]
大佬您好！
   我想请问一下您这篇文章中的变化检测标签是如何生成的，在论文中似乎没有详细解释.

**Comment by chenhaiwen** [comment]
标签应该是数据集中本来就有的吧，但大佬，我想学习下ChangeMask的代码，没找到。

**Comment by Z-Zheng** [comment]
感谢大家关注！

1. 标签是数据集自带的；
2. ChangeMask的代码涉及到一些协议问题，会晚一些放出，可以关注我的主页查看相关资源的具体情况

这是我们采用的SECOND数据集划分方式，如果在此期间需要和ChangeMask对比精度，可以利用这个划分测一下模型
SECOND dataset: [train](https://zhuozheng.top/assets/changemask/SECOND/train.csv) / [val](https://zhuozheng.top/assets/changemask/SECOND/val.csv) split (ours)

**Comment by wuhucheng** [comment]
大佬，能分享一下changemask的代码吗

**Comment by 15738281321** [comment]
@Z-Zheng 
I would like to ask the author, can you share the relevant code of ChangeMask now?

**Comment by lxllzzy** [comment]
老师，有代码吗

**Comment by Z-Zheng** [comment]
The code of ChangeMask has been released at https://github.com/Z-Zheng/pytorch-change-models/blob/main/torchange/models/changemask.py 

If you are interested in our latest study about change, please focus on https://github.com/Z-Zheng/pytorch-change-models

**Comment by lxllzzy** [comment]
Okay, thank you, teacher
