### ISSUE TITLE
Some questions about table 1 of the paper

### ISSUE THREAD

**Issue by WesternTrail** [Z-Zheng/ChangeStar#25]
The picture mentioned in the paper is a comparison between changestar and some segmentation model FPN for change detection. It may be that I don't know much about segmentation. how Can the segmentation network mentioned in the table be used for change detection? How are they compared? I hope the author can explain, thank you！

![image](https://user-images.githubusercontent.com/28615285/222377514-f633f962-3a8b-472a-a3ed-92b252c5d4ca.png)

**Comment by Z-Zheng** [comment]
PCC, post-classification comparison.
You can obtain two segmentation masks by any semantic segmentation model, then compare them to generate a change mask.

**Comment by WesternTrail** [comment]
@Z-Zheng thank you!
